version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 3.1
  build:
    commands:
      - dotnet build
      - dotnet test
artifacts:
  files:
    - AppSpec.yaml
    - outputtemplate.yaml