version: 0.2
phases:
  build:
    commands:
      - > 
        aws cloudformation package 
        --template-file lambdatemplate.yaml 
        -- s3-bucket "david-ting-lambda-functions"
        --output-template-file outputtemplate.yml
      
artifacts:
  type: zip
  files:
    - lambdatemplate.yaml
    - outputtemplate.yaml