version: 0.2
phases:
  build:
    commands:
      - dotnet restore
      - dotnet build
      - > 
        aws cloudformation package 
        --template-file lambdatemplate.yaml 
        --s3-bucket "david-ting-lambda-functions"
        --output-template-file outputtemplate.yml
      
artifacts:
  type: zip
  files:
    - ./bin/Debug/netcoreapp3.0
    - lambdatemplate.yaml
    - outputtemplate.yaml