version: 0.2
phases:
  pre_build:
    commands:
      - bash ./build_commands/$Action/build.sh
  build:
    commands:
      - bash ./build_commands/$Action/package.sh
    
artifacts:
  type: zip
  files:
    - "**/*"
