version: 0.1
phases:
  install:
    commands:
      - aws codedeploy package --template-file AppSpec.yaml --s3-bucket david-ting-lambda-functions --output-template-file outputtemplate.yaml
artifacts:
  type: zip
  files:
    - AppSpec.yaml
    - outputtemplate.yaml