version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 3.1
  pre_build:
    commands:
      - echo Restore started on `date`
      - cd HelloWorld/src/HelloWorld
      - dotnet clean
      - dotnet restore
  build:
    commands:
      - echo Build started on `date`
      - > 
        aws cloudformation package 
        --template-file lambdatemplate.yaml 
        --s3-bucket "david-ting-dn-lambda-deployment-artifacts"
        --output-template-file outputtemplate.yaml
      
artifacts:
  type: zip
  files:
    - ./bin/Debug/netcoreapp3.1/publish
    - lambdatemplate.yaml
    - outputtemplate.yaml