version: 0.2
phases:
  pre_build:
    commands:
      - mkdir -p ./build_commands/$Action
      - touch ./build_commands/$Action/pre_build.sh
      - bash ./build_commands/$Action/pre_build.sh
  build:
    commands:
      - touch ./build_commands/$Action/build.sh 
      - bash ./build_commands/$Action/build.sh
  post_build:
    commands:
      - touch ./build_commands/$Action/post_build.sh
      - bash ./build_commands/$Action/post_build.sh
    
artifacts:
  type: zip
  files:
    - "**/*"
