AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Lambda functions for HelloWorldAPI

Globals:
  Function:
    Runtime: dotnetcore3.1
    CodeUri: ./

Resources:
  HelloWorldDNFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: HelloWorld::HelloWorld.HelloWorldHandler::HelloWorld
      Role: arn:aws:iam::741922737521:role/david-ting-helloworld-stack-HelloWorldFunctionRole-YMHECZ7NFYSH
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Canary10Percent5Minutes
        Alarms:
          - !Ref HelloWorldDNFunctionAlarm
      Events:
        HelloWorldDNApi:
          Type: Api
          Properties:
            Path: /
            Method: GET

  GetPeopleDNFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: HelloWorld::HelloWorld.GetPeopleNamesHandler::GetPeopleNames
      Role: arn:aws:iam::741922737521:role/david-ting-helloworld-stack-HelloWorldFunctionRole-YMHECZ7NFYSH
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Canary10Percent5Minutes
        Alarms:
          - !Ref GetPeopleDNFunctionAlarm
      Events:
        HelloWorldDNApi:
          Type: Api
          Properties:
            Path: /people
            Method: GET

  AddPersonDNFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: HelloWorld::HelloWorld.AddPersonHandler::AddPerson
      Role: arn:aws:iam::741922737521:role/david-ting-helloworld-stack-HelloWorldFunctionRole-YMHECZ7NFYSH
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Canary10Percent5Minutes
        Alarms:
          - !Ref AddPersonDNFunctionAlarm
      Events:
        HelloWorldDNApi:
          Type: Api
          Properties:
            Path: /people
            Method: POST

  DeletePersonDNFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: HelloWorld::HelloWorld.DeletePersonHandler::DeletePerson
      Role: arn:aws:iam::741922737521:role/david-ting-helloworld-stack-HelloWorldFunctionRole-YMHECZ7NFYSH
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Canary10Percent5Minutes
        Alarms:
          - !Ref DeletePersonDNFunctionAlarm
      Events:
        HelloWorldDNApi:
          Type: Api
          Properties:
            Path: /people/{id}
            Method: DELETE

  UpdatePersonDNFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: HelloWorld::HelloWorld.UpdatePersonHandler::UpdatePerson
      Role: arn:aws:iam::741922737521:role/david-ting-helloworld-stack-HelloWorldFunctionRole-YMHECZ7NFYSH
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Canary10Percent5Minutes
        Alarms:
          - !Ref UpdatePersonDNFunctionAlarm
      Events:
        HelloWorldDNApi:
          Type: Api
          Properties:
            Path: /people/{id}
            Method: PUT

  HelloWorldDNFunctionAlarm: 
    Type: AWS::CloudWatch::Alarm
    Properties: &alarmProps
      AlarmDescription: "Triggered if Lambda Function errors out at least once"
      Namespace: AWS/Lambda
      MetricName: Errors
      Statistic: Sum
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      DatapointsToAlarm: 1
      EvaluationPeriods: 5
      Period: 60
      Dimensions:
        - Name: LambdaFunctionName
          Value: !Ref HelloWorldDNFunction

  GetPeopleDNFunctionAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      <<: *alarmProps
      Dimensions:
        - Name: LambdaFunctionName
          Value: !Ref GetPeopleDNFunction
            
  AddPersonDNFunctionAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      <<: *alarmProps
      Dimensions:
        - Name: LambdaFunctionName
          Value: !Ref AddPersonDNFunction

  DeletePersonDNFunctionAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      <<: *alarmProps
      Dimensions:
        - Name: LambdaFunctionName
          Value: !Ref DeletePersonDNFunction

  UpdatePersonDNFunctionAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      <<: *alarmProps
      Dimensions:
        - Name: LambdaFunctionName
          Value: !Ref UpdatePersonDNFunction