AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A sample SAM template for deploying Lambda functions.
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: HelloWorldHandler.HelloWorld
      Runtime: dotnetcore3.1
      Code: ./HelloWorld/
      Events:
        HelloWorldAPI:
          type: Api
          Properties:
            Path: /