AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Lambda functions for HelloWorldAPI

Globals:
  Function:
    Runtime: dotnetcore3.1
    CodeUri: ./

Resources:
  HelloWorldDNFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: HelloWorld::HelloWorld.HelloWorldHandler::HelloWorld
      Role: arn:aws:iam::741922737521:role/david-ting-helloworld-stack-HelloWorldFunctionRole-YMHECZ7NFYSH
#      AutoPublishAlias: live
#      DeploymentPreference:
#        Type: Canary10Percent5Minutes
      Events:
        HelloWorldDNApi:
          Type: Api
          Properties:
            Path: /
            Method: GET

  GetPeopleDNFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: HelloWorld::HelloWorld.GetPeopleNamesHandler::GetPeopleNames
      Role: arn:aws:iam::741922737521:role/david-ting-helloworld-stack-HelloWorldFunctionRole-YMHECZ7NFYSH
#      AutoPublishAlias: live
#      DeploymentPreference:
#        Type: Canary10Percent5Minutes
      Events:
        HelloWorldDNApi:
          Type: Api
          Properties:
            Path: /people
            Method: GET

  AddPersonDNFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: HelloWorld::HelloWorld.AddPersonHandler::AddPerson
      Role: arn:aws:iam::741922737521:role/david-ting-helloworld-stack-HelloWorldFunctionRole-YMHECZ7NFYSH
#      AutoPublishAlias: live
#      DeploymentPreference:
#        Type: Canary10Percent5Minutes
      Events:
        HelloWorldDNApi:
          Type: Api
          Properties:
            Path: /people
            Method: POST

  DeletePersonDNFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: HelloWorld::HelloWorld.DeletePersonHandler::DeletePerson
      Role: arn:aws:iam::741922737521:role/david-ting-helloworld-stack-HelloWorldFunctionRole-YMHECZ7NFYSH
#      AutoPublishAlias: live
#      DeploymentPreference:
#        Type: Canary10Percent5Minutes
      Events:
        HelloWorldDNApi:
          Type: Api
          Properties:
            Path: /people/{id}
            Method: DELETE

  UpdatePersonDNFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: HelloWorld::HelloWorld.UpdatePersonHandler::UpdatePerson
      Role: arn:aws:iam::741922737521:role/david-ting-helloworld-stack-HelloWorldFunctionRole-YMHECZ7NFYSH
#      AutoPublishAlias: live
#      DeploymentPreference:
#        Type: Canary10Percent5Minutes
      Events:
        HelloWorldDNApi:
          Type: Api
          Properties:
            Path: /people/{id}
            Method: PUT

  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: david-ting-helloworld-lambda-error-alarm
      AlarmDescription: "Alarm if lambda errors out too many times"
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: HelloWorldDNFunction
      Statistics: Sum
      ComparisonOperator: GreaterThanThreshold
      Threshold: 0
      EvaluationPeriods: 5
      Period: 60
      TreatMissingData: breaching