AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Lambda functions for HelloWorldAPI

Globals:
  Function:
    Runtime: dotnetcore3.1

Resources:
  HelloWorldDNFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://david-ting-lambda-functions/HelloWorldHandler.zip
      Handler: HelloWorld::HelloWorld.HelloWorldHandler::HelloWorld
      Role: arn:aws:iam::741922737521:role/david-ting-helloworld-stack-HelloWorldFunctionRole-YMHECZ7NFYSH
      Events:
        HelloWorldDNApi:
          Type: Api
          Properties:
            Path: /
            Method: GET

  GetPeopleDNFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://david-ting-lambda-functions/david-ting-GetPeopleNamesHandler.zip
      Handler: HelloWorld::HelloWorld.GetPeopleNamesHandler::GetPeopleNames
      Role: arn:aws:iam::741922737521:role/david-ting-helloworld-stack-HelloWorldFunctionRole-YMHECZ7NFYSH
      Events:
        HelloWorldDNApi:
          Type: Api
          Properties:
            Path: /people
            Method: GET

  AddPersonDNFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://david-ting-lambda-functions/david-ting-AddPersonHandler.zip
      Handler: HelloWorld::HelloWorld.AddPersonHandler::AddPerson
      Role: arn:aws:iam::741922737521:role/david-ting-helloworld-stack-HelloWorldFunctionRole-YMHECZ7NFYSH
      Events:
        HelloWorldDNApi:
          Type: Api
          Properties:
            Path: /people
            Method: POST

  DeletePersonDNFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://david-ting-lambda-functions/david-ting-DeletePersonHandler.zip
      Handler: HelloWorld::HelloWorld.DeletePersonHandler::DeletePerson
      Role: arn:aws:iam::741922737521:role/david-ting-helloworld-stack-HelloWorldFunctionRole-YMHECZ7NFYSH
      Events:
        HelloWorldDNApi:
          Type: Api
          Properties:
            Path: /people/{name}
            Method: DELETE

  UpdatePersonDNFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://david-ting-lambda-functions/david-ting-UpdatePersonHandler.zip
      Handler: HelloWorld::HelloWorld.UpdatePersonHandler::UpdatePerson
      Role: arn:aws:iam::741922737521:role/david-ting-helloworld-stack-HelloWorldFunctionRole-YMHECZ7NFYSH
      Events:
        HelloWorldDNApi:
          Type: Api
          Properties:
            Path: /people/{name}
            Method: PUT
